### ISSUE TITLE
multiple time point analysis issue

### ISSUE THREAD

**Issue by AVines21** [mochrielab/3DMembraneReconstruction#4]
This is Amanda Vines from Megan King's lab. I'm using the code to analyze particles from .dv movies, with 3 channels of information, 25 Z slices, and 31 time points captured though I only want to look at one channel for analysis. Trying to run them through the code as is (with the channel of interest set for particles and the other two channels turned off) resulted in an error message. Then I saved them in .tif format to reduce from 3 channels to 1 channel (still 25 Z slices, 31 time points) and it runs fine. But when I open the .csv file, the data seems to only be from the first time point or recorded as "0", even though there are rows for each particle at each time point. So somehow it isn't recognizing the rest of the time points in the .tif file for analysis (though it does seem to be reading them in the reconstruction phase of the code running). I've attached a screenshot of the .csv file, showing the rows for the first particle. Please let me know if there is any other information that would be helpful in resolving this issue. Thank you!
![03 ch2 data screenshot](https://cloud.githubusercontent.com/assets/22329159/18684536/93ef215c-7f42-11e6-9fd4-33e62b869f86.PNG)

**Comment by yao-zhao** [comment]
Thanks, I will fix that, can you share me the movie through google drive at yao.zhao@yale.edu

**Comment by AVines21** [comment]
Ok, it's shared!

**Comment by yao-zhao** [comment]
it is fixed. it now correctly output values for each frame. however when I looked at your movie and realized that the motion between each frame is very large. the current program is designed to track particles with small motion under noisy condition, it will miss the particle after frame 1.
